#!/bin/bash

echo '####################################################################'
echo '| google-chrome-stable installation instructions:                  |'
echo '####################################################################'
echo '| wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -'
echo '| echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
echo '| apt update && apt install -y google-chrome-stable'
echo '####################################################################'
